INSERT INTO parties (partyAbbr,partyName) VALUES
("ADP","American Delta Party"),
("AIP","American Independent"),
("AM","American Party"),
("AMC","American Constitution Party"),
("AMP","America’s Party"),
("APV","Approval Voting Party"),
("ASP","American Solidarity Party"),
("BFA","Better for America"),
("BP","By Petition"),
("C","Conservative"),
("CCS","Courage Character Service"),
("CON","Constitution"),
("CPF","Constitution Party of Florida"),
("D","Democratic"),
("DFL","Democratic-Farmer Labor"),
("DNL","Democratic-Nonpartisan League"),
("GI","Green Independent"),
("GPF","Green Party of Florida"),
("GR","Green-Rainbow"),
("GRE","Green"),
("IAP","Independent American  Party"),
("IDP","Independence"),
("IG","Iowa Green"),
("IND","Independent"),
("IOC","It's Our Children"),
("IPC","Independent People of Colorado"),
("KFP","Kotlikoff for President"),
("LBF","Libertarian Party of Florida"),
("LBU","Liberty Union"),
("LFC","Life, Family, Constitution"),
("LIB","Libertarian"),
("LMN","Legal Marijuana Now"),
("LTC","Loyal Trustworthy Compassion"),
("MTP","Mountain Party"),
("N","Nonpartisan"),
("NAF","Nonaffiliated"),
("NLP","Natural Law Party"),
("NP","Nominated by Petition"),
("NPI","New Independent Party Iowa"),
("NPY","No Political Party"),
("NRP","Nonviolent Resistance/Pacifist"),
("NTP","Nutrition Party"),
("P","Prohibition Party"),
("PAF","Peace and Freedom"),
("PG","Pacific Green"),
("PRO","Progressive"),
("PSL","Party for Socialism and Liberation"),
("R","Republican"),
("RPF","Reform Party of Florida"),
("SEA","Socialism Equality Anti-War"),
("SLP","Socialism and Liberation Party"),
("SOC","Socialist Party USA"),
("STG","Statehood Green"),
("SWP","Socialist Workers Party"),
("UN","Unaffiliated"),
("UST","U.S. Taxpayers"),
("VP","Veterans Party"),
("VPA","Veterans Party of America"),
("WEP","Women's Equality Party"),
("WF","Working Families"),
("WG","Wisconsin Green"),
("WW","Workers World");

INSERT INTO affiliations2016 (candidateID,partyAbbr) VALUES
("1","APV"),
("2","AMC"),
("2","CON"),
("2","CPF"),
("2","IAP"),
("2","IND"),
("2","UST"),
("3","D"),
("3","DFL"),
("3","DNL"),
("3","WEP"),
("3","WF"),
("4","CON"),
("5","ADP"),
("5","IND"),
("5","NAF"),
("5","NP"),
("5","NPY"),
("5","RPF"),
("5","UN"),
("6","N"),
("7","IAP"),
("8","IND"),
("8","P"),
("9","AMP"),
("9","LFC"),
("10","LTC"),
("11","IDP"),
("11","IND"),
("11","LBF"),
("11","LIB"),
("11","N"),
("12","IND"),
("12","NPI"),
("13","VPA"),
("13","VP"),
("14","IND"),
("14","SWP"),
("14","UN"),
("15","IAP"),
("16","IOC"),
("16","KFP"),
("17","LBU"),
("17","PAF"),
("17","PSL"),
("17","SLP"),
("18","NRP"),
("19","IPC"),
("20","ASP"),
("21","CCS"),
("21","IDP"),
("21","IND"),
("21","BFA"),
("21","NP"),
("21","UN"),
("22","UN"),
("22","WW"),
("23","UN"),
("24","NTP"),
("25","AM"),
("26","IND"),
("26","UN"),
("27","NLP"),
("27","SOC"),
("28","BP"),
("28","GI"),
("28","GPF"),
("28","GR"),
("28","GRE"),
("28","IG"),
("28","IND"),
("28","MTP"),
("28","PG"),
("28","PRO"),
("28","STG"),
("28","UN"),
("28","WG"),
("29","C"),
("29","AIP"),
("29","R"),
("30","LMN"),
("31","SEA");