CREATE DATABASE prezplaypro;

CREATE TABLE candidates (
  candidateID int(2) NOT NULL,
  candidateName varchar(72) NOT NULL,
  PRIMARY KEY (candidateID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE parties (
  partyAbbr varchar(3) NOT NULL,
  partyName varchar(72) NOT NULL,
  PRIMARY KEY (partyAbbr)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE states (
  stateAbbr varchar(2) NOT NULL,
  stateName varchar(72) NOT NULL,
  PRIMARY KEY (stateAbbr)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE electoralCollege (
  stateAbbr varchar(2) NOT NULL,
  year1992 int(2) NOT NULL,
  year2004 int(2) NOT NULL,
  year2012 int(2) NOT NULL,
  FOREIGN KEY (stateAbbr) REFERENCES states (stateAbbr)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE affiliations (
	candidateID int(2) NOT NULL,
	partyAbbr varchar(3) NOT NULL,
	year int(4) NOT NULL,
	FOREIGN KEY (candidateID) REFERENCES candidates (candidateID),
	FOREIGN KEY (partyAbbr) REFERENCES parties (partyAbbr),
  INDEX (candidateID),
	INDEX (partyAbbr),
  INDEX (year)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE results2016 (
  stateAbbr varchar(2) NOT NULL,
  candidateID int(2) NOT NULL,
  popVotes int(7) NOT NULL,
  FOREIGN KEY (candidateID) REFERENCES candidates (candidateID),
  FOREIGN KEY (stateAbbr) REFERENCES states (stateAbbr),
  INDEX (stateAbbr),
  INDEX (candidateID),
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO candidates2016 (candidateID, candidateName) VALUES 
(01,'Frank Atwood'), 
(02,'Darrell L. Castle'), 
(03,'Hillary Clinton'), 
(04,'Scott Copeland'), 
(05,'Roque "Rocky" De La Fuente'), 
(06,'Richard Duncan'), 
(07,'Rocky Giordani'), 
(08,'James "Jim" Hedges'), 
(09,'Tom Hoefling'), 
(10,'Princess Jacob'), 
(11,'Gary Johnson'), 
(12,'Lynn S. Kahn'), 
(13,'Chris Keniston'), 
(14,'Alyson Kennedy'), 
(15,'Kyle Kenley Kopitke'), 
(16,'Laurence Kotlikoff'), 
(17,'Gloria Estela La Riva'), 
(18,'Bradford Lyttle'), 
(19,'Joseph Allen Maldonado'), 
(20,'Michael A. Maturen'), 
(21,'Evan McMullin'), 
(22,'Monica Moorehead'), 
(23,'Ryan Alan Scott'), 
(24,'Rod Silva'), 
(25,'Peter Skewes'), 
(26,'Mike Smith'), 
(27,'Emidio Soltysik'), 
(28,'Jill Stein'), 
(29,'Donald J. Trump'), 
(30,'Dan R. Vacek'), 
(31,'Jerry White');

INSERT INTO states (stateAbbr,stateName) VALUES
('AL','Alabama'),
('AK','Alaska'),
('AZ','Arizona'),
('AR','Arkansas'),
('CA','California'),
('CO','Colorado'),
('CT','Connecticut'),
('DE','Delaware'),
('DC','District of Columbia'),
('FL','Florida'),
('GA','Georgia'),
('HI','Hawaii'),
('ID','Idaho'),
('IL','Illinois'),
('IN','Indiana'),
('IA','Iowa'),
('KS','Kansas'),
('KY','Kentucky'),
('LA','Louisiana'),
('ME','Maine'),
('MD','Maryland'),
('MA','Massachusetts'),
('MI','Michigan'),
('MN','Minnesota'),
('MS','Mississippi'),
('MO','Missouri'),
('MT','Montana'),
('NE','Nebraska'),
('NV','Nevada'),
('NH','New Hampshire'),
('NJ','New Jersey'),
('NM','New Mexico'),
('NY','New York'),
('NC','North Carolina'),
('ND','North Dakota'),
('OH','Ohio'),
('OK','Oklahoma'),
('OR','Oregon'),
('PA','Pennsylvania'),
('RI','Rhode Island'),
('SC','South Carolina'),
('SD','South Dakota'),
('TN','Tennessee'),
('TX','Texas'),
('UT','Utah'),
('VT','Vermont'),
('VA','Virginia'),
('WA','Washington'),
('WV','West Virginia'),
('WI','Wisconsin'),
('WY','Wyoming');

INSERT INTO parties (partyAbbr,partyName) VALUES
("ADP","American Delta Party"),
("AIP","American Independent"),
("AM","American Party"),
("AMC","American Constitution Party"),
("AMP","America’s Party"),
("APV","Approval Voting Party"),
("ASP","American Solidarity Party"),
("BFA","Better for America"),
("BP","By Petition"),
("C","Conservative"),
("CCS","Courage Character Service"),
("CON","Constitution"),
("CPF","Constitution Party of Florida"),
("D","Democratic"),
("DFL","Democratic-Farmer Labor"),
("DNL","Democratic-Nonpartisan League"),
("GI","Green Independent"),
("GPF","Green Party of Florida"),
("GR","Green-Rainbow"),
("GRE","Green"),
("IAP","Independent American  Party"),
("IDP","Independence"),
("IG","Iowa Green"),
("IND","Independent"),
("IOC","It's Our Children"),
("IPC","Independent People of Colorado"),
("KFP","Kotlikoff for President"),
("LBF","Libertarian Party of Florida"),
("LBU","Liberty Union"),
("LFC","Life, Family, Constitution"),
("LIB","Libertarian"),
("LMN","Legal Marijuana Now"),
("LTC","Loyal Trustworthy Compassion"),
("MTP","Mountain Party"),
("N","Nonpartisan"),
("NAF","Nonaffiliated"),
("NLP","Natural Law Party"),
("NP","Nominated by Petition"),
("NPI","New Independent Party Iowa"),
("NPY","No Political Party"),
("NRP","Nonviolent Resistance/Pacifist"),
("NTP","Nutrition Party"),
("P","Prohibition Party"),
("PAF","Peace and Freedom"),
("PG","Pacific Green"),
("PRO","Progressive"),
("PSL","Party for Socialism and Liberation"),
("R","Republican"),
("RPF","Reform Party of Florida"),
("SEA","Socialism Equality Anti-War"),
("SLP","Socialism and Liberation Party"),
("SOC","Socialist Party USA"),
("STG","Statehood Green"),
("SWP","Socialist Workers Party"),
("UN","Unaffiliated"),
("UST","U.S. Taxpayers"),
("VP","Veterans Party"),
("VPA","Veterans Party of America"),
("WEP","Women's Equality Party"),
("WF","Working Families"),
("WG","Wisconsin Green"),
("WW","Workers World");

INSERT INTO affiliations2016 (candidateID,partyAbbr) VALUES
("1","APV"),
("2","AMC"),
("2","CON"),
("2","CPF"),
("2","IAP"),
("2","IND"),
("2","UST"),
("3","D"),
("3","DFL"),
("3","DNL"),
("3","WEP"),
("3","WF"),
("4","CON"),
("5","ADP"),
("5","IND"),
("5","NAF"),
("5","NP"),
("5","NPY"),
("5","RPF"),
("5","UN"),
("6","N"),
("7","IAP"),
("8","IND"),
("8","P"),
("9","AMP"),
("9","LFC"),
("10","LTC"),
("11","IDP"),
("11","IND"),
("11","LBF"),
("11","LIB"),
("11","N"),
("12","IND"),
("12","NPI"),
("13","VPA"),
("13","VP"),
("14","IND"),
("14","SWP"),
("14","UN"),
("15","IAP"),
("16","IOC"),
("16","KFP"),
("17","LBU"),
("17","PAF"),
("17","PSL"),
("17","SLP"),
("18","NRP"),
("19","IPC"),
("20","ASP"),
("21","CCS"),
("21","IDP"),
("21","IND"),
("21","BFA"),
("21","NP"),
("21","UN"),
("22","UN"),
("22","WW"),
("23","UN"),
("24","NTP"),
("25","AM"),
("26","IND"),
("26","UN"),
("27","NLP"),
("27","SOC"),
("28","BP"),
("28","GI"),
("28","GPF"),
("28","GR"),
("28","GRE"),
("28","IG"),
("28","IND"),
("28","MTP"),
("28","PG"),
("28","PRO"),
("28","STG"),
("28","UN"),
("28","WG"),
("29","C"),
("29","AIP"),
("29","R"),
("30","LMN"),
("31","SEA");