CREATE TABLE spectrum (
	partyAbbr varchar(3) NOT NULL,
	rating int(1) NOT NULL,
	FOREIGN KEY (partyAbbr) REFERENCES parties (partyAbbr),
	INDEX (rating)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO spectrum (partyAbbr,rating) VALUES 
("IDP","3"),
("IOC","3"),
("KFP","3"),
("RPF","3"),
("NTP","3"),
("ADP","2"),
("D","2"),
("DFL","2"),
("DNL","2"),
("LTC","2"),
("BFA","4"),
("R","4"),
("VP","4"),
("APV","0"),
("BP","0"),
("IND","0"),
("IPC","0"),
("N","0"),
("NAF","0"),
("NP","0"),
("NPY","0"),
("UN","0"),
("WEP","0"),
("AIP","5"),
("AM","5"),
("AMC","5"),
("AMP","5"),
("C","5"),
("CCS","5"),
("CON","5"),
("CPF","5"),
("IAP","5"),
("LBF","5"),
("LFC","5"),
("LIB","5"),
("NLP","5"),
("P","5"),
("UST","5"),
("VPA","5"),
("ASP","1"),
("GI","1"),
("GPF","1"),
("GR","1"),
("GRE","1"),
("IG","1"),
("LBU","1"),
("LMN","1"),
("MTP","1"),
("NPI","1"),
("NRP","1"),
("PAF","1"),
("PG","1"),
("PRO","1"),
("PSL","1"),
("SEA","1"),
("SLP","1"),
("SOC","1"),
("STG","1"),
("SWP","1"),
("WF","1"),
("WG","1"),
("WW","1");